version: '3.4'

services:
  deploy:
    env_file:
      - .env
    build:
      context: .
    volumes:
    - '~/.aws:/root/.aws'

  logs:
    build:
      context: .
      dockerfile: sam.dockerfile
    command: logs -n Fn --stack-name $STACK_NAME --profile $AWS_PROFILE --tail
    volumes:
    - '~/.aws:/root/.aws'

  ghost:
    image: ghost:3.20.1
    environment:
      DEBUG: '*'
      logging__level: debug
    ports:
      - 80:80
      - 2368:2368
      - 4200:4200

  release:
    build:
      context: .
    entrypoint: scripts/sam-release.sh
    volumes:
      - '~/.aws:/root/.aws'

  smtp-password:
    build:
      context: smtp/
    command:
      - --region
      - $AWS_DEFAULT_REGION
      - --secret
      - $YOUR_IAM_SECRET_ACCESS_KEY

  static-site:
    build:
      context: static-site
    env_file:
      - .env
    network_mode: host
    ports:
    - 8080:8080
